CREATE TABLE "family_members" (
	"id" text PRIMARY KEY NOT NULL,
	"member_id" text NOT NULL,
	"name" text NOT NULL,
	"relation" text,
	"dob" date,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "members" (
	"id" text PRIMARY KEY NOT NULL,
	"member_code" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "members_member_code_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1001 CACHE 1),
	"civil_id_no" text NOT NULL,
	"name" text NOT NULL,
	"dob" date,
	"email" text,
	"photo_key" text,
	"gsm_no" text,
	"whatsapp_no" text,
	"blood_group" text,
	"profession" text,
	"family_status" text,
	"residential_area" text,
	"passport_no" text,
	"address_india" text,
	"tel_no_india" text,
	"is_family_in_oman" boolean DEFAULT false NOT NULL,
	"application_no" text,
	"received_on" date,
	"submitted_by" text,
	"shakha_india" text,
	"checked_by" text,
	"approved_by" text,
	"president" text,
	"secretary" text,
	"union" text,
	"district" text,
	"shakha_id" text NOT NULL,
	"is_archived" boolean DEFAULT false NOT NULL,
	"archived_at" timestamp,
	"is_lifetime" boolean DEFAULT false NOT NULL,
	"active_from" date,
	"expiry" date,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "family_members" ADD CONSTRAINT "family_members_member_id_members_id_fk" FOREIGN KEY ("member_id") REFERENCES "public"."members"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "members" ADD CONSTRAINT "members_shakha_id_shakhas_id_fk" FOREIGN KEY ("shakha_id") REFERENCES "public"."shakhas"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "family_members_member_id_idx" ON "family_members" USING btree ("member_id");--> statement-breakpoint
CREATE UNIQUE INDEX "members_member_code_unique" ON "members" USING btree ("member_code");--> statement-breakpoint
CREATE UNIQUE INDEX "members_civil_id_no_unique" ON "members" USING btree ("civil_id_no");--> statement-breakpoint
CREATE INDEX "members_shakha_id_idx" ON "members" USING btree ("shakha_id");--> statement-breakpoint
CREATE INDEX "members_active_from_idx" ON "members" USING btree ("active_from");--> statement-breakpoint
CREATE INDEX "members_expiry_idx" ON "members" USING btree ("expiry");